version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8001:8001
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8001
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 54322:5432
    environment:
      - POSTGRES_DB=POS
      - POSTGRES_USER=Rana
      - POSTGRES_PASSWORD=Raw@1994
    container_name: postgres_db