# Generated by Django 3.2.22 on 2023-10-30 10:46

from django.db import migrations


def create_initial_data(apps, schema_editor):
    ProductType = apps.get_model('inventory', 'ProductType')
    data = [{"id": 1, "name": "proin risus praesent"}, {"id": 2, "name": "tellus nulla ut"},
            {"id": 3, "name": "adipiscing"}, {"id": 4, "name": "maecenas"}, {"id": 5, "name": "commodo vulputate"},
            {"id": 6, "name": "sed"}, {"id": 7, "name": "laoreet ut rhoncus"}, {"id": 8, "name": "libero"},
            {"id": 9, "name": "felis fusce"}, {"id": 10, "name": "habitasse"},
            {"id": 11, "name": "duis aliquam convallis"}, {"id": 12, "name": "sit amet"},
            {"id": 13, "name": "amet nunc"}, {"id": 14, "name": "nisl duis bibendum"},
            {"id": 15, "name": "vel dapibus at"}, {"id": 16, "name": "vestibulum"}, {"id": 17, "name": "dolor vel"},
            {"id": 18, "name": "mauris eget"}, {"id": 19, "name": "morbi ut odio"},
            {"id": 20, "name": "mattis nibh ligula"}, {"id": 21, "name": "duis"}, {"id": 22, "name": "morbi"},
            {"id": 23, "name": "porttitor lacus at"}, {"id": 24, "name": "elit proin interdum"},
            {"id": 25, "name": "quam"}, {"id": 26, "name": "sem praesent"}, {"id": 27, "name": "a"},
            {"id": 28, "name": "amet"}, {"id": 29, "name": "cum"}, {"id": 30, "name": "fusce"},
            {"id": 31, "name": "eleifend donec"}, {"id": 32, "name": "sit amet"},
            {"id": 33, "name": "turpis donec posuere"}, {"id": 34, "name": "eu sapien cursus"},
            {"id": 35, "name": "velit nec"}, {"id": 36, "name": "pede"}, {"id": 37, "name": "volutpat quam"},
            {"id": 38, "name": "amet diam"}, {"id": 39, "name": "tristique tortor"}, {"id": 40, "name": "vivamus in"},
            {"id": 41, "name": "in congue"}, {"id": 42, "name": "ac enim in"}, {"id": 43, "name": "ut erat curabitur"},
            {"id": 44, "name": "arcu adipiscing molestie"}, {"id": 45, "name": "consectetuer adipiscing elit"},
            {"id": 46, "name": "eget eros elementum"}, {"id": 47, "name": "dapibus"},
            {"id": 48, "name": "tortor risus"}, {"id": 49, "name": "neque libero convallis"},
            {"id": 50, "name": "sed tincidunt eu"}]

    for item in data:
        id_value = item['id']
        name = item['name']

        ProductType.objects.create(id=id_value, name=name)


class Migration(migrations.Migration):
    dependencies = [('inventory', '0003_auto_20231030_0311'), ]

    operations = [
            migrations.RunPython(create_initial_data)
    ]

