# Generated by Django 3.2.22 on 2023-10-30 11:23

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Barcode = apps.get_model('inventory', 'Barcode')
    data = [{"name": "EAN"}, {"name": "UPC"}, {"name": "ITF"}, {"name": "C39"}, {"name": "CBR"}, {"name": "C28"}]

    for item in data:
        name = item['name']

        Barcode.objects.create(name=name)


class Migration(migrations.Migration):
    dependencies = [('inventory', '0004_auto_20231030_0346'), ]

    operations = [migrations.RunPython(create_initial_data)]
