# Generated by Django 3.2.22 on 2023-10-30 11:29

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    data = [{"id": 1, "code": "ab096c99-92f4-4b5b-aa6c-c799dce583c8", "name": "Carolina Selwood"},
            {"id": 2, "code": "1512e32c-2efa-49c7-871f-1d6ab8f3a6fa", "name": "Brittani Hanaby"},
            {"id": 3, "code": "25e8959f-7fd2-4856-93c1-3a6d1128c658", "name": "Vernon McKeady"},
            {"id": 4, "code": "cf1495d9-cc3f-4102-8c8a-32924e294503", "name": "Elie Rossoni"},
            {"id": 5, "code": "0435fb6e-e191-4026-95bf-0a78568cd631", "name": "Stefan Dowbekin"},
            {"id": 6, "code": "cec08dfa-a65d-421c-ae55-e67e21a93652", "name": "Hank Brahms"},
            {"id": 7, "code": "3b8e21fc-e526-4615-893f-f1fedccca35d", "name": "Nickie Baltzar"},
            {"id": 8, "code": "51532203-9414-455d-8b95-d01756d11dc1", "name": "Mathew Brecknock"},
            {"id": 9, "code": "26b39e79-ff2b-4e38-8cd1-5143a9221174", "name": "Rianon Vasilmanov"},
            {"id": 10, "code": "f0e1b3ba-a6f6-42b2-86cd-2495c5602183", "name": "Frasquito Burn"},
            {"id": 11, "code": "9f451878-b667-4199-b4ea-5373d20e6510", "name": "Radcliffe Conelly"},
            {"id": 12, "code": "cb4118b6-21cb-4ba0-9335-1f4ee8548d2f", "name": "Cyndie Brushfield"},
            {"id": 13, "code": "d12fba30-7470-443f-9e1f-723da4a6dc47", "name": "Tallia Crosio"},
            {"id": 14, "code": "bb0885fd-bfb9-4ecb-b6e1-d5fdb6967f01", "name": "Marney Stut"},
            {"id": 15, "code": "0e8f150b-bbb1-4a1e-9541-d5420d3611fd", "name": "Eilis Boyda"},
            {"id": 16, "code": "935ebfc3-83fb-41da-bfe0-ef48dcce5497", "name": "Katey Odam"},
            {"id": 17, "code": "9b8f087f-77f6-431a-8b07-c33700b0c7b1", "name": "Brok Leavey"},
            {"id": 18, "code": "51c75809-bb70-4843-ae20-8edae0ee2626", "name": "Ethelred Euesden"},
            {"id": 19, "code": "48de1e39-6e96-44b9-8c34-5237ed216904", "name": "Rouvin D'Souza"},
            {"id": 20, "code": "eed23b2d-f714-4e9f-9ad9-23eb6968d144", "name": "Sarine Bellino"},
            {"id": 21, "code": "99b63766-a3e3-43f3-b045-a0050ab8b00c", "name": "Gherardo Took"},
            {"id": 22, "code": "aa173349-2a53-4653-a229-58f7d2030228", "name": "Orion Vasey"},
            {"id": 23, "code": "d0ca4b9c-454c-4589-856b-af3906e41a73", "name": "Dill Devenish"},
            {"id": 24, "code": "e2116f64-28a0-4aaf-91f2-371aa6b65b49", "name": "Nikolaus Shyram"},
            {"id": 25, "code": "bc1fad84-6bbd-4086-b643-79a700b66935", "name": "Foss Hustler"},
            {"id": 26, "code": "64f4cb3b-eeec-4898-a63e-c848b5a1885d", "name": "Baryram Pont"},
            {"id": 27, "code": "6192931b-eb27-4e31-aeb1-e6c37d246129", "name": "Faun Hartus"},
            {"id": 28, "code": "1eca618b-8e8a-4759-a1b2-58f5a53730be", "name": "Adan Sweedy"},
            {"id": 29, "code": "16b11c61-9951-43bd-ba28-67d682b324c2", "name": "Kaye Peckett"},
            {"id": 30, "code": "1a678dc4-e09e-4dd7-b101-fc47ab0a14e1", "name": "Glyn Pellatt"},
            {"id": 31, "code": "ad314d91-e2c1-49e3-a40a-32503fbe2617", "name": "Rosanna Stockle"},
            {"id": 32, "code": "3a55c501-9ee5-4389-ac17-f1b4c52ba709", "name": "Charmion Etheridge"},
            {"id": 33, "code": "1e63a853-f90d-4671-b615-b133cea8cbd7", "name": "Lambert Yusupov"},
            {"id": 34, "code": "1c219e10-7ecd-4e94-8e69-53396e9fdd19", "name": "Blake Schenfisch"},
            {"id": 35, "code": "a79509dc-9824-4790-93a0-1f03b379e266", "name": "Neda Anand"},
            {"id": 36, "code": "6c103d9e-5b0e-4084-b747-746e9c2e21a1", "name": "Joline Shellshear"},
            {"id": 37, "code": "4fcbf529-e2d2-4991-b41d-0cb945ef149d", "name": "Dale Calveley"},
            {"id": 38, "code": "136e4a05-09a9-418b-a67a-c56a975e4298", "name": "Sibyl Bourrel"},
            {"id": 39, "code": "abe490c1-e24d-48bf-8e1e-ab455c164f4e", "name": "Ahmad Almon"},
            {"id": 40, "code": "02b71232-91c2-4792-ad06-8b8a48a886ac", "name": "Wynn Liversedge"},
            {"id": 41, "code": "8af0dab3-70c2-4c21-bbc2-45c0f1966244", "name": "Shelly Spurnier"},
            {"id": 42, "code": "fd3a6fa8-d771-4025-ad02-4b6d0209faac", "name": "Kattie Dillon"},
            {"id": 43, "code": "4170ab2d-6a4d-4123-89d4-15da7b791e73", "name": "Ned Milella"},
            {"id": 44, "code": "aa73f5c2-6400-49d0-8c5c-b299c5d05ab6", "name": "Jeffy Ludlam"},
            {"id": 45, "code": "106212b7-2c2a-4e98-bbc9-52b789c3ca4b", "name": "Everett Gunstone"},
            {"id": 46, "code": "dc5b7458-6ebd-4139-b389-28d1534829f8", "name": "Francine Dooley"},
            {"id": 47, "code": "fe5ef5ce-5075-4006-9378-69729b03dd69", "name": "Roxane Birkmyre"},
            {"id": 48, "code": "aeb418fd-d632-4a1f-97e2-31c9ef9a0f2c", "name": "Mickie Marusik"},
            {"id": 49, "code": "e351c769-a63d-430a-b0c5-a33395a8f280", "name": "Bert de Zamora"},
            {"id": 50, "code": "de65fa9c-cecc-4db7-b4d4-a87b75f33326", "name": "Johann Mixer"}]

    for item in data:
        id_value = item['id']
        code = item['code']
        name = item['name']

        Category.objects.create(id=id_value, code=code, name=name)


class Migration(migrations.Migration):
    dependencies = [('inventory', '0005_auto_20231030_0423'), ]

    operations = [
            migrations.RunPython(create_initial_data)
    ]
