# Generated by Django 3.2.22 on 2023-10-30 15:01

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    ProductType = apps.get_model('inventory', 'ProductType')
    Barcode = apps.get_model('inventory', 'Barcode')
    Category = apps.get_model('inventory', 'Category')
    type = ProductType.objects.get(name='adipiscing')
    barcode = Barcode.objects.filter(name='UPC').first()
    category = Category.objects.get(name='Carolina Selwood')
    print(f'{type}-{barcode}-{category}')

    data = [{"name": "Shurlock Ruthven", "code": "6152b996-e294-47fc-b866-6919e3d9d37c", "cost": 19, "price": 23,
             "tax_method": "In", "alert_quantity": 3},
            {"name": "Yetta Foulger", "code": "b99171af-3d78-46f0-b148-e06b5ea6cd6e", "cost": 14, "price": 3,
             "tax_method": "In", "alert_quantity": 2},
            {"name": "Kaycee Proud", "code": "384b37ec-996e-4b1f-b148-52dccfd32dc7", "cost": 95, "price": 54,
             "tax_method": "In", "alert_quantity": 5},
            {"name": "Skippie Slowey", "code": "f149ed30-2381-4698-81f7-9651ed87a43c", "cost": 81, "price": 82,
             "tax_method": "In", "alert_quantity": 9},
            {"name": "Anallise Betjeman", "code": "922453a9-54b9-4539-a195-e9365cf04137", "cost": 25, "price": 32,
             "tax_method": "In", "alert_quantity": 7},
            {"name": "Marleah Whytock", "code": "98418e6c-7d56-4822-9d84-a8efda731eec", "cost": 6, "price": 34,
             "tax_method": "Ex", "alert_quantity": 6}]

    for items in data:
        name = items['name']
        code = items['code']
        cost = items['cost']
        price = items['price']
        tax_method = items['tax_method']
        alert_quantity = items['alert_quantity']

        Product.objects.create(type=type, name=name, code=code, barcode_symbology=barcode, category=category,
                               cost=cost, price=price, tax_method=tax_method, alert_quantity=alert_quantity)


class Migration(migrations.Migration):
    dependencies = [('inventory', '0007_auto_20231030_0446'), ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
