# Generated by Django 3.2.22 on 2023-10-30 16:02

from django.db import migrations


def create_initial_data(apps, schema_editor):
    PurchaseOrder = apps.get_model('inventory', 'PurchaseOrder')
    Supplier = apps.get_model('inventory', 'Supplier')
    data = [{"date": "2023-01-15", "reference": "lorem vitae", "total": 1171, "status": "R"},
            {"date": "2023-10-27", "reference": "ornare imperdiet sapien", "total": 6098, "status": "N"},
            {"date": "2023-10-14", "reference": "pede justo eu massa donec", "total": 3712, "status": "N"},
            {"date": "2023-03-08", "reference": "augue vestibulum rutrum rutrum neque aenean", "total": 6718,
             "status": "R"}, {"date": "2023-05-03", "reference": "arcu", "total": 5041, "status": "N"},
            {"date": "2023-08-12", "reference": "sed magna at nunc commodo placerat", "total": 3828, "status": "N"},
            {"date": "2023-02-10", "reference": "vitae consectetuer eget rutrum", "total": 9006, "status": "N"},
            {"date": "2023-09-22", "reference": "tellus nulla ut erat id mauris vulputate elementum nullam varius",
             "total": 8191, "status": "R"},
            {"date": "2023-07-23", "reference": "mauris vulputate elementum nullam", "total": 5979, "status": "N"},
            {"date": "2023-09-06", "reference": "sit amet eleifend pede libero quis orci", "total": 1987,
             "status": "R"},
            {"date": "2022-11-01", "reference": "vehicula condimentum curabitur in libero ut massa", "total": 1239,
             "status": "N"}, {"date": "2022-11-02", "reference": "accumsan", "total": 5673, "status": "N"},
            {"date": "2022-11-07", "reference": "ante ipsum primis in faucibus orci luctus", "total": 620,
             "status": "N"},
            {"date": "2022-12-23", "reference": "ac neque duis bibendum", "total": 8791, "status": "R"},
            {"date": "2022-11-03",
             "reference": "nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh", "total": 202,
             "status": "N"}, {"date": "2023-05-20", "reference": "ultricies eu nibh", "total": 8568, "status": "R"},
            {"date": "2023-05-11", "reference": "lobortis vel dapibus at diam nam", "total": 3667, "status": "N"},
            {"date": "2023-06-05", "reference": "placerat", "total": 8599, "status": "N"},
            {"date": "2023-10-25", "reference": "orci luctus et ultrices", "total": 7946, "status": "N"},
            {"date": "2023-10-01", "reference": "volutpat sapien arcu sed augue aliquam", "total": 8014, "status": "N"},
            {"date": "2023-03-29", "reference": "scelerisque quam turpis adipiscing lorem vitae", "total": 8862,
             "status": "N"},
            {"date": "2023-09-10", "reference": "volutpat in congue etiam justo etiam pretium iaculis justo",
             "total": 8386, "status": "R"},
            {"date": "2022-11-19", "reference": "vitae ipsum", "total": 874, "status": "R"},
            {"date": "2023-02-21", "reference": "adipiscing molestie hendrerit at vulputate vitae nisl aenean",
             "total": 6213, "status": "N"},
            {"date": "2023-07-17", "reference": "eros suspendisse accumsan tortor quis turpis sed ante", "total": 7153,
             "status": "R"}]
    for items in data:
        date = items['date']
        reference = items['reference']
        total = items['total']
        status = items['status']

        PurchaseOrder.objects.create(date=date, reference=reference, total=total,
                                     supplier=Supplier.objects.get(name='Dewitt Oehm'), status=status)


class Migration(migrations.Migration):
    dependencies = [('inventory', '0008_auto_20231030_0801'), ]

    operations = [migrations.RunPython(create_initial_data)]
