# Generated by Django 3.2.22 on 2023-10-30 16:20

from django.db import migrations


def create_initial_data(apps, schema_editor):
    PurchaseOrderItem = apps.get_model('inventory', 'PurchaseOrderItem')
    PurchaseOrder = apps.get_model('inventory', 'PurchaseOrder')
    Product = apps.get_model('inventory', 'Product')

    data = [{"price": 8658, "quantity": 15, "total": 3982}, {"price": 1321, "quantity": 38, "total": 87176},
            {"price": 7480, "quantity": 14, "total": 72989}, {"price": 6709, "quantity": 9, "total": 75542},
            {"price": 8562, "quantity": 1, "total": 22555}, {"price": 8631, "quantity": 6, "total": 12882},
            {"price": 5512, "quantity": 58, "total": 95076}, {"price": 3554, "quantity": 12, "total": 13234},
            {"price": 4590, "quantity": 8, "total": 32161}, {"price": 8285, "quantity": 59, "total": 18567},
            {"price": 2833, "quantity": 45, "total": 17124}, {"price": 602, "quantity": 32, "total": 23216},
            {"price": 5228, "quantity": 97, "total": 44209}, {"price": 6814, "quantity": 60, "total": 35998},
            {"price": 2327, "quantity": 41, "total": 36329}, {"price": 3987, "quantity": 42, "total": 91240},
            {"price": 2971, "quantity": 30, "total": 32241}, {"price": 1437, "quantity": 24, "total": 62518},
            {"price": 4914, "quantity": 38, "total": 97928}, {"price": 5253, "quantity": 78, "total": 32939},
            {"price": 5767, "quantity": 82, "total": 76534}, {"price": 9557, "quantity": 55, "total": 30356},
            {"price": 8272, "quantity": 48, "total": 86665}, {"price": 111, "quantity": 25, "total": 21887},
            {"price": 4166, "quantity": 32, "total": 85776}]
    purchase_order = PurchaseOrder.objects.get(id=1)
    product = Product.objects.get(id=2)
    for items in data:
        price = items['price']
        quantity = items['quantity']
        total = items['total']

        PurchaseOrderItem.objects.create(product=product, purchase_order=purchase_order, price=price, quantity=quantity,
                                         total=total)


class Migration(migrations.Migration):
    dependencies = [('inventory', '0010_auto_20231030_0909'), ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
