# Generated by Django 3.2.22 on 2023-10-30 16:31

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Expense = apps.get_model('inventory', 'Expense')

    data = [{"date": "2022-12-19", "reference": "donec odio justo", "amount": 92163},
            {"date": "2023-03-07", "reference": "placerat praesent blandit nam", "amount": 2263},
            {"date": "2022-12-31", "reference": "volutpat", "amount": 40352},
            {"date": "2022-12-07", "reference": "id", "amount": 84968},
            {"date": "2023-07-01", "reference": "purus eu", "amount": 41601},
            {"date": "2023-05-20", "reference": "enim sit amet nunc viverra", "amount": 17460},
            {"date": "2022-11-04", "reference": "nibh fusce lacus", "amount": 18971},
            {"date": "2023-04-26", "reference": "gravida sem praesent", "amount": 4508},
            {"date": "2023-10-07", "reference": "curabitur at ipsum ac", "amount": 1073},
            {"date": "2023-04-30", "reference": "molestie", "amount": 14861},
            {"date": "2023-04-09", "reference": "viverra diam", "amount": 97082},
            {"date": "2023-06-04", "reference": "risus", "amount": 78750},
            {"date": "2023-05-08", "reference": "lectus in", "amount": 56922},
            {"date": "2023-08-08", "reference": "dignissim vestibulum vestibulum", "amount": 71885},
            {"date": "2023-04-07", "reference": "nulla", "amount": 54955},
            {"date": "2022-11-20", "reference": "pretium nisl ut volutpat sapien", "amount": 85092},
            {"date": "2023-06-16", "reference": "sodales sed tincidunt eu", "amount": 86749},
            {"date": "2023-09-30", "reference": "a ipsum integer", "amount": 38398},
            {"date": "2023-07-22", "reference": "amet cursus id turpis integer", "amount": 46721},
            {"date": "2023-06-24", "reference": "quis orci eget", "amount": 62598},
            {"date": "2023-06-14", "reference": "est risus", "amount": 81864},
            {"date": "2023-08-15", "reference": "posuere", "amount": 11550},
            {"date": "2023-01-10", "reference": "turpis sed ante vivamus", "amount": 60420},
            {"date": "2022-12-14", "reference": "mauris morbi", "amount": 69137},
            {"date": "2023-07-29", "reference": "ut at", "amount": 65387}]

    for item in data:
        date = item['date']
        reference = item['reference']
        amount = item['amount']

        Expense.objects.create(date=date, reference=reference, amount=amount)


class Migration(migrations.Migration):
    dependencies = [('inventory', '0011_auto_20231030_0920'), ]

    operations = [
            migrations.RunPython(create_initial_data)
    ]
