# Generated by Django 3.2.23 on 2023-11-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name_plural': 'Purchase Orders'},
        ),
    ]
