# Generated by Django 3.2.23 on 2023-11-16 07:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
