# Generated by Django 3.2.23 on 2023-11-16 07:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_purchaseorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
