# Generated by Django 3.2.23 on 2023-11-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_purchaseorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('R', 'Received'), ('N', 'Not Received Yet')], default='N', max_length=250),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorders', to='inventory.supplier'),
        ),
    ]
