# Generated by Django 3.2.22 on 2023-10-27 22:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('customer_custom_field_1', models.CharField(blank=True, max_length=250, null=True)),
                ('customer_custom_field_2', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='POS.customer'),
        ),
    ]
