# Generated by Django 3.2.22 on 2023-10-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('POS', '0006_auto_20231030_1016'), ]

    operations = [
        migrations.AlterField(model_name='sale', name='order_tax', field=models.FloatField(blank=True, null=True), ), ]
