# Generated by Django 3.2.22 on 2023-10-31 06:26

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Sale = apps.get_model('POS', 'Sale')
    Customer = apps.get_model('POS', 'Customer')

    data = [{"total_items": 798, "total_price": 63744, "total_payable": 458708, "status": "P"},
            {"total_items": 923, "total_price": 35464, "total_payable": 138485, "status": "P"},
            {"total_items": 310, "total_price": 48502, "total_payable": 890772, "status": "P"},
            {"total_items": 341, "total_price": 55972, "total_payable": 274116, "status": "P"},
            {"total_items": 874, "total_price": 13520, "total_payable": 849650, "status": "H"},
            {"total_items": 50, "total_price": 18867, "total_payable": 625454, "status": "P"},
            {"total_items": 493, "total_price": 96463, "total_payable": 593582, "status": "P"},
            {"total_items": 41, "total_price": 29286, "total_payable": 193098, "status": "H"},
            {"total_items": 717, "total_price": 36734, "total_payable": 108615, "status": "H"},
            {"total_items": 270, "total_price": 36625, "total_payable": 722962, "status": "H"},
            {"total_items": 421, "total_price": 43855, "total_payable": 899922, "status": "H"},
            {"total_items": 367, "total_price": 52929, "total_payable": 5318, "status": "H"},
            {"total_items": 796, "total_price": 56114, "total_payable": 962413, "status": "H"},
            {"total_items": 264, "total_price": 70378, "total_payable": 400864, "status": "H"},
            {"total_items": 502, "total_price": 14393, "total_payable": 789564, "status": "H"},
            {"total_items": 220, "total_price": 51207, "total_payable": 553362, "status": "H"},
            {"total_items": 408, "total_price": 47261, "total_payable": 946115, "status": "H"},
            {"total_items": 354, "total_price": 55204, "total_payable": 732720, "status": "H"},
            {"total_items": 261, "total_price": 846, "total_payable": 714844, "status": "H"},
            {"total_items": 65, "total_price": 88465, "total_payable": 344298, "status": "H"},
            {"total_items": 259, "total_price": 32721, "total_payable": 697082, "status": "P"},
            {"total_items": 496, "total_price": 6360, "total_payable": 705310, "status": "P"},
            {"total_items": 887, "total_price": 4430, "total_payable": 123965, "status": "H"},
            {"total_items": 398, "total_price": 82724, "total_payable": 243469, "status": "H"},
            {"total_items": 350, "total_price": 44689, "total_payable": 88398, "status": "P"},
            {"total_items": 84, "total_price": 33978, "total_payable": 201990, "status": "P"},
            {"total_items": 837, "total_price": 24867, "total_payable": 387073, "status": "H"}]

    for item in data:
        total_items = item['total_items']
        total_price = item['total_price']
        total_payable = item['total_payable']
        status = item['status']

        Sale.objects.create(total_items=total_items, total_price=total_price, total_payable=total_payable,
                            customer=Customer.objects.get(id=1), status=status)


class Migration(migrations.Migration):
    dependencies = [('POS', '0007_alter_sale_order_tax'), ]

    operations = [migrations.RunPython(create_initial_data)]
