# Generated by Django 3.2.22 on 2023-10-31 06:28

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Sale = apps.get_model('POS', 'Sale')
    SaleItem = apps.get_model('POS', 'SaleItem')

    data = [{"price": 738, "quantity": 88746, "total": 172452}, {"price": 930, "quantity": 96112, "total": 814971},
            {"price": 549, "quantity": 62373, "total": 3055}, {"price": 763, "quantity": 10867, "total": 857435},
            {"price": 515, "quantity": 50953, "total": 865643}, {"price": 763, "quantity": 18424, "total": 511810},
            {"price": 684, "quantity": 67518, "total": 613148}, {"price": 138, "quantity": 82734, "total": 339225},
            {"price": 240, "quantity": 74291, "total": 952639}, {"price": 713, "quantity": 16512, "total": 317732},
            {"price": 731, "quantity": 79972, "total": 100375}, {"price": 812, "quantity": 71228, "total": 819695},
            {"price": 780, "quantity": 28655, "total": 263056}, {"price": 231, "quantity": 596, "total": 301759},
            {"price": 338, "quantity": 47002, "total": 22466}, {"price": 492, "quantity": 74746, "total": 257915},
            {"price": 511, "quantity": 18751, "total": 321744}, {"price": 281, "quantity": 46645, "total": 776504},
            {"price": 703, "quantity": 75518, "total": 215846}, {"price": 384, "quantity": 97315, "total": 370488},
            {"price": 854, "quantity": 4179, "total": 958348}, {"price": 403, "quantity": 71971, "total": 751894},
            {"price": 60, "quantity": 48216, "total": 240008}, {"price": 739, "quantity": 21828, "total": 734492},
            {"price": 232, "quantity": 91163, "total": 943452}, {"price": 30, "quantity": 95984, "total": 686253},
            {"price": 920, "quantity": 75952, "total": 493079}, {"price": 828, "quantity": 35559, "total": 736064},
            {"price": 921, "quantity": 57558, "total": 845077}, {"price": 392, "quantity": 79350, "total": 959326},
            {"price": 922, "quantity": 13050, "total": 787586}, {"price": 29, "quantity": 46161, "total": 795947},
            {"price": 975, "quantity": 97697, "total": 810003}, {"price": 269, "quantity": 97783, "total": 36566},
            {"price": 885, "quantity": 30691, "total": 119504}, {"price": 37, "quantity": 11587, "total": 393567},
            {"price": 775, "quantity": 43310, "total": 380803}, {"price": 234, "quantity": 33369, "total": 608037},
            {"price": 405, "quantity": 77718, "total": 858648}, {"price": 550, "quantity": 84943, "total": 724232},
            {"price": 583, "quantity": 26223, "total": 924972}, {"price": 986, "quantity": 14667, "total": 57784},
            {"price": 279, "quantity": 6397, "total": 758420}, {"price": 713, "quantity": 39660, "total": 303109},
            {"price": 257, "quantity": 12348, "total": 928294}, {"price": 332, "quantity": 72210, "total": 894460},
            {"price": 524, "quantity": 87793, "total": 168782}, {"price": 83, "quantity": 34105, "total": 429624},
            {"price": 183, "quantity": 91644, "total": 132951}, {"price": 821, "quantity": 71979, "total": 274568}]

    product = Product.objects.get(id=1)
    sale = Sale.objects.get(id=2)

    for item in data:
        price = item['price']
        quantity = item['quantity']
        total = item['total']

        SaleItem.objects.create(product=product, sale=sale, price=price, quantity=quantity, total=total)


class Migration(migrations.Migration):
    dependencies = [('POS', '0008_auto_20231030_2326'), ]

    operations = [
            migrations.RunPython(create_initial_data)
    ]
