# Generated by Django 3.2.22 on 2023-10-31 06:37

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Sale = apps.get_model('POS', 'Sale')
    Payment = apps.get_model('POS', 'Payment')

    data = [{"amount": 4257, "payment_by": "Ep"}, {"amount": 68319, "payment_by": "Ch"},
            {"amount": 64510, "payment_by": "Ep"}, {"amount": 5067, "payment_by": "Ch"},
            {"amount": 53412, "payment_by": "Ca"}, {"amount": 60552, "payment_by": "Ca"},
            {"amount": 99878, "payment_by": "Ep"}, {"amount": 95318, "payment_by": "Ch"},
            {"amount": 99223, "payment_by": "Ch"}, {"amount": 57137, "payment_by": "Ca"},
            {"amount": 98019, "payment_by": "Ca"}, {"amount": 9862, "payment_by": "Ep"},
            {"amount": 1429, "payment_by": "Ca"}, {"amount": 42569, "payment_by": "Cd"},
            {"amount": 43640, "payment_by": "Cd"}, {"amount": 23196, "payment_by": "Cd"},
            {"amount": 94515, "payment_by": "Ep"}, {"amount": 16072, "payment_by": "Cd"},
            {"amount": 12606, "payment_by": "Ep"}, {"amount": 54370, "payment_by": "Ch"},
            {"amount": 35427, "payment_by": "Ca"}, {"amount": 43387, "payment_by": "Cd"},
            {"amount": 1718, "payment_by": "Ch"}, {"amount": 99407, "payment_by": "Ch"},
            {"amount": 11908, "payment_by": "Ca"}, {"amount": 12623, "payment_by": "Ep"},
            {"amount": 97752, "payment_by": "Ch"}, {"amount": 97164, "payment_by": "Ep"},
            {"amount": 6698, "payment_by": "Ep"}, {"amount": 24390, "payment_by": "Ca"},
            {"amount": 77538, "payment_by": "Ch"}, {"amount": 83284, "payment_by": "Ep"},
            {"amount": 29736, "payment_by": "Cd"}, {"amount": 33555, "payment_by": "Ep"},
            {"amount": 73084, "payment_by": "Ep"}, {"amount": 92075, "payment_by": "Ep"},
            {"amount": 97350, "payment_by": "Ch"}, {"amount": 3014, "payment_by": "Cd"},
            {"amount": 15754, "payment_by": "Ch"}, {"amount": 91863, "payment_by": "Ca"},
            {"amount": 60684, "payment_by": "Ca"}, {"amount": 73440, "payment_by": "Cd"},
            {"amount": 49220, "payment_by": "Ch"}, {"amount": 38515, "payment_by": "Ca"},
            {"amount": 33884, "payment_by": "Ep"}, {"amount": 97637, "payment_by": "Ca"},
            {"amount": 64637, "payment_by": "Ep"}, {"amount": 38449, "payment_by": "Ep"},
            {"amount": 78643, "payment_by": "Ep"}, {"amount": 99181, "payment_by": "Ca"}]

    sale = Sale.objects.get(id=2)

    for item in data:
        amount = item['amount']
        payment_by = item['payment_by']

        Payment.objects.create(sale=sale, amount=amount, payment_by=payment_by)


class Migration(migrations.Migration):
    dependencies = [('POS', '0009_auto_20231030_2328'), ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
