# Generated by Django 3.2.22 on 2023-10-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0011_auto_20231030_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
