# Generated by Django 3.2.23 on 2023-11-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0015_alter_storeproduct_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(default='Walk-in Client', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='POS.customer'),
        ),
    ]
