# Generated by Django 3.2.23 on 2023-11-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0016_alter_sale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(default='Walk-in Client', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='POS.customer'),
        ),
    ]
