# Generated by Django 3.2.23 on 2023-11-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0020_auto_20231106_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='POS.customer'),
        ),
    ]
