# Generated by Django 3.2.23 on 2023-11-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0025_alter_sale_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
