# Generated by Django 3.2.23 on 2023-11-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0031_auto_20231109_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_by',
            field=models.CharField(choices=[('Ca', 'Cash'), ('Ch', 'Cheque'), ('Cd', 'Card'), ('Ep', 'Easy-Paisa')], default='Ca', max_length=250),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
