# Generated by Django 3.2.23 on 2023-11-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0032_auto_20231110_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
