# Generated by Django 3.2.23 on 2023-11-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0037_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
