# Generated by Django 3.2.23 on 2023-11-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0039_auto_20231120_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='total_cash',
        ),
        migrations.AlterField(
            model_name='pos',
            name='closing_cash_in_hand',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
