# Generated by Django 3.2.23 on 2023-11-22 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POS', '0041_alter_pos_opening_cash_in_hand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ManyToManyField(related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
