# Generated by Django 3.2.23 on 2023-11-22 08:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POS', '0042_auto_20231122_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='POS',
            new_name='Register',
        ),
    ]
