# Generated by Django 3.2.23 on 2023-11-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0043_rename_pos_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
