# Generated by Django 3.2.23 on 2023-12-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0044_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Walk-in Client', max_length=250),
        ),
    ]
