# Generated by Django 3.2.23 on 2023-12-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0045_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Open'), ('C', 'Close')], max_length=10, null=True),
        ),
    ]
