# Generated by Django 3.2.23 on 2023-12-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0046_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close')], max_length=10),
        ),
    ]
