# Generated by Django 3.2.23 on 2023-12-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0050_remove_payment_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='payment',
            field=models.ForeignKey(default=115, on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='POS.payment'),
            preserve_default=False,
        ),
    ]
