# Generated by Django 3.2.22 on 2023-10-27 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_auto_20231027_1538'),
        ('user_accounts', '0002_auto_20231027_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='POS.store'),
            preserve_default=False,
        ),
    ]
