# Generated by Django 3.2.23 on 2023-11-02 10:33

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_accounts', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Groups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
