# Generated by Django 3.2.23 on 2023-11-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='store',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
