from django.urls import path
from POS import views

urlpatterns = [
    path('stores', views.StoreListView.as_view(), name='stores'),
    path('create_sale_register/<int:register_id>/<int:store_id>', views.POS.as_view(), name='create-sale'),
    path('update_sale_item/', views.SaleItemUpdateView.as_view(), name='update-sale-item'),
    path('update_sale/<int:pk>/<int:store_id>', views.POSUpdateView.as_view(), name='update-sale'),
    path('delete_sale/<int:pk>', views.POSDeleteView.as_view(), name='delete-sale'),
    path('create_customer', views.AddCustomerView.as_view(), name='create-customer'),
    path('create_payment', views.PaymentView.as_view(), name='create-payment'),
    path('hold_sale', views.HoldOrderView.as_view(), name='hold-sale'),
    path('delete_saleitem', views.DeleteSaleItemView.as_view(), name='delete-saleitem'),
    path('create_sale_product/<int:prod_id>', views.SaleView.as_view(), name='create-sale-product'),
    path('create_store', views.AddStoreView.as_view(), name='create-store'),
    path('add_customer', views.AddCustomersView.as_view(), name='add-customer'),
    path('list_customers', views.ListCustomersView.as_view(), name='list-customers'),
    path('update_customer/<int:pk>', views.UpdateCustomerView.as_view(), name='update-customer'),
    path('delete_customer/<int:pk>', views.DeleteCustomerView.as_view(), name='delete-customer'),
    path('list_products', views.ProductListView.as_view(), name='list-products'),
    path('add_product', views.AddProductView.as_view(), name='add-product'),
    path('update_product/<int:pk>', views.UpdateProductView.as_view(), name='update-product'),
    path('delete_product/<int:pk>', views.DeleteProductView.as_view(), name='delete-product'),
    path('list_products/<int:pk>', views.StoreWiseProductListView.as_view(), name='list-products-by-store'),
    path('list_sales', views.SaleListView.as_view(), name='list-sales'),
    path('list_opened_bills', views.OpenedBillsView.as_view(), name='list-opened-bills'),
    path('select_store/<int:store_id>', views.StoreSelectView.as_view(), name='select-store'),
    path('cash_in_hand', views.CashInHandView.as_view(), name='cash-in-hand'),
    path('close_register', views.CloseRegisterView.as_view(), name='close_register'),
    path('daily_report', views.DailyReportView.as_view(), name='daily_report'),
    path('monthly_report', views.MonthlyReportView.as_view(), name='monthly_report'),
    path('sales_report', views.SalesReportView.as_view(), name='sales_report'),
    path('sales_report_filter', views.FilterSalesReportView.as_view(), name='sales_report_filter'),
    path('payment_report', views.PaymentReportView.as_view(), name='payment_report'),
    path('payment_report_filter', views.FilterPaymentsReportView.as_view(), name='payment_report_filter'),
    path('registers_report', views.RegisterReportView.as_view(), name='register_report'),
    path('registers_report_filter', views.FilterRegistersReportView.as_view(), name='register_report_filter'),
    path('top_products', views.TopProductsView.as_view(), name='top-products'),
    path('top_products_report', views.TopProductsReportView.as_view(), name='top-products-report'),
    path('top_products_filter', views.FilterProductsReportView.as_view(), name='top-products-filter'),
    path('customer_screen', views.CustomerScreenView.as_view(), name='customer-screen'),
    path('customer_screen_update', views.CustomerScreenUpdateView.as_view(), name='customer-screen-update'),
]
